### ISSUE TITLE
你好，请问win7上怎么用？

### ISSUE THREAD

**Issue by jerry011235** [HYSkyline/wallbase#1]
cmd运行报错。
"……\Python34\python.exe" "%~dp0wlb_chief.py"

**Comment by HYSkyline** [comment]
你好！
不好意思刚刚上线，才看到。
首先我的运行环境是python2.7.10，而python3以上版本向下存在兼容性问题。也许是这个原因导致你运行报错。刚才我重新运行了一次，输出结果仍然是正常的。
能否贴出你报错的所有内容？

**Comment by jerry011235** [comment]
你好，真感谢你的回复。
我是先 `download ZIP` 到`E:\图片\download\wallbase-master\wallbase-master`，
然后把 `python27.dll` 、 `python27.exe` 和 `python27.zip` 这三个文件复制到wallbase-master文件夹里。
然后写了个批处理，代码是

``` c
"%~dp0python27.exe" "%~dp0wlb_chief.py"
@pause
```

运行后报错内容：

```
E:\图片\download\wallbase-master\wallbase-master>"E:\图片\download\wallbase-mast
er\wallbase-master\python27.exe" "E:\图片\download\wallbase-master\wallbase-mast
er\wlb_chief.py"
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "E:\图片\download\wallbase-master\wallbase-master\wlb_chief.py", line 3,
in <module>
    import requests
ImportError: No module named requests
请按任意键继续. . .
```

似乎是第三行，没有请求到requests模块？另外我不用便携版的python27，直接官网下载python-2.7.10.msi，还是一样报错，是第三行 import requests
ImportError: No module named requests。

**Comment by HYSkyline** [comment]
是这样，requests是一个第三方模块，需要用pip命令安装的，你运行之前有装过嚒？另外代码里的lxml模块也是第三方模块也需要自己安装。如果你没有装的话当然就没法运行啦= =
另外需要注意的是我没有在环境里声明编码环境为utf-8，中文路径的话有一定的可能你接下来还会遇到编码错误之类的问题，希望不会发生啦^ ^
